version: "3.7"
services:
  db:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: test-123
      MYSQL_DATABASE: vem
    volumes:
      - db-data:/var/lib/mysql/
  phpmyadmin:
    image: phpmyadmin:5.2.1
    container_name: PhpMyAdmin
    restart: always
    ports:
      - 5013:80
    environment:
      - PMA_ARBITRARY=0
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=test-123
  front:
    image: skabrits/vem_front:dev
    restart: always
    ports:
      - "3000:80"
    environment:
      REACT_APP_API_BASE_URL: "http://localhost:8000"
  back:
    image: skabrits/vem_server:dev
    privileged: true
    restart: always
    ports:
      - "8000:8000"
    environment:
      DB_PROVIDER: "MySQL"
      DB_ENDPOINT: db
      DB_CONNECTIONS: 2
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock
volumes:
  db-data: